### PR TITLE
Raytracing update

### PR DESCRIPTION
**Pull request by AlexReimann**
@bit-pirate @stonier 

Outline:
The raytracing in the voxel layer currently is not clearing everything. To get rid of this problem, padded clearing and clearing corner cases was introduced. See also [here](https://github.com/ros-planning/navigation/issues/267).

The algorithm first needed to be speeded up significantly to handle the additional computation cost for the padding. This was done through separating [the costmap updating](https://github.com/ros-planning/navigation/blob/85459b056e636665fadcbf66851160faa54c23b8/voxel_grid/include/voxel_grid/voxel_grid.h#L370) to [a step](https://github.com/ros-planning/navigation/blob/85459b056e636665fadcbf66851160faa54c23b8/voxel_grid/include/voxel_grid/voxel_grid.h#L370) [afterwards](https://github.com/yujinrobot/navigation/blob/indigo-devel/costmap_2d/plugins/voxel_layer.cpp#L345). I also separated the [actual update for the voxel grid](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/src/voxel_grid.cpp#L274) and the ["calculation" of the bit mask](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/include/voxel_grid/grid_mask_updater.h#L34) which is used to determine the z position of update. The padding can make the bit mask [over- or underflow](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/include/voxel_grid/grid_mask_updater.h#L40) which gives erronous results. [The error has to be corrected](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/src/voxel_grid.cpp#L323) before applying the mask and thus the seperation was needed.

The number of voxels which are updated more than once by the rays is quite high as the number of voxels << number of rays. This is why a fixed size array is used for saving the updates. This speeds up the performance as we don't need to allocate or check anything for an update.
E. g. as we go through a ray we would have save which voxel we clear. One voxel could be cleared by 10 rays. We either could explicitly save the clearing of the voxel 10 times, which takes time for memory allocation, or do a check if we already have a clearing for that voxel, which takes time for searching / checking.
With the array we can simply mark a voxel for clearing without changing anything. If we mark it twice it won't change anything.
For the voxel grid the clearing is [done by a bitmask](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/include/voxel_grid/grid_mask_updater.h#L17) which specifies the z position of the voxel.

The size of the array was first choosen as the size of the voxel layer. This leads to problems with big costmaps. Thus the [max_raytrace_range_ parameter](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/costmap_2d/plugins/obstacle_layer.cpp#L90) was added in the obstacle layer to get the maximum updated area which is [used for the array size](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/costmap_2d/plugins/voxel_layer.cpp#L250).

The padding is done with the 4 neighbouring pixels on the dominant axis (the axis with the longest ray proportion, see [Bresenham algorithm](http://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm). E. g. if the dominant axis is x it will also [clear the y+-1 and z+-1](https://github.com/yujinrobot/navigation/blob/a43cc338e967fc11ec65e9ac995bc5da125e90b1/voxel_grid/include/voxel_grid/grid_mask_updater.h#L40).

For configuration following parameters  are added:
  `padded_raytracing`
  `raytrace_corner_cases`

Usable in common_costmaps in the layer which uses the voxel grid (same place where z_resolution of the voxel layer etc. is)

Also adds project settings for voxel grid and costmap_2d

### CODE REVIEW

**Comment by bit-pirate** [comment]
Rest looks OK, but I haven't gone into the details of the updating/clearing logic.

Let's test this after you have followed up on the comments above.

**Comment by AlexReimann** [comment]
Updated

**Comment by AlexReimann** [comment]
Updated comments
Added fix for big maps

**Comment by bit-pirate** [comment]
LGTM!

**Pull request merged**
